### ISSUE TITLE
ConfigurationChanged 事件的理解

### ISSUE THREAD

**Issue by leehuian** [WeihanLi/StackExchange.Redis-docs-cn#1]
你好，一直没搞明白ConfigurationChanged 事件是在什么情况下触发的，解释说是 连接对象内部修改，也是一脸懵逼，能给举一个例子吗

**Comment by WeihanLi** [comment]
`StackExchange.Redis` 会在内部检查你的配置里指定的redis server，如果有一个节点有状态变化，比如有一个down掉了或者有一个挂掉的重新启动了，都会触发这个事件。


这里有一个[示例](https://github.com/WeihanLi/WeihanLi.Redis/blob/930e8afd1a8abdbdda131b707d9e94a6ec5ef964/samples/WeihanLi.Redis.Samples/ConfigurationChangedEventSample.cs)

你可以下载这个示例项目在本地运行，可以通过 docker 启动 redis-server

``` bash
docker run -d -p 16379:6379 --name redis16379 redis:alpine
```

然后启动项目之后，停掉某一个 docker 容器

``` bash
docker stop redis16379
```

停掉之后重新启动
``` bash
docker start redis16379
```

查看控制台输出日志

![image](https://user-images.githubusercontent.com/7604648/56942892-9b15db00-6b4f-11e9-9a41-cbf820ea131e.png)

**Comment by WeihanLi** [comment]
@leehuian  不知道这个示例是否可以解答你的疑惑，这里先把这个 issue 关掉了，如果有问题可以再打开

**Comment by leehuian** [comment]
3q,前两天休假了，之前测试了下，在使用SE的时候，如果配置的连接信息不完整，SE会自动获取完整的集群信息，同时会触发该事件：
eg：
集群节点是： 
主：ip1:6379,ip2:6379,ip3:6379
从：ip1:6380，ip2:6380，ip2:6380
如果我设置connectionString的时候，只提供了主节点的，会触发该事件
